CXX=g++
CPPFLAGS= -c

SOURCES=R2.cpp tp3_1_1.cpp tp3_1_2.cpp tp3_1_3.cpp tp3_2_1.cpp tp3_2_2.cpp tp3_2_3.cpp
OBJECTS=$(SOURCES:%.cpp=%.o)

EXECUTABLE=tp3

#all: $(EXECUTABLE)
#    $(CXX) $^ -o $@ $(CXXFLAGS) $(LDFLAGS) $(LDLIBS)

#$(EXECUTABLE): $(OBJECTS)   

#R2.o tp3_1_1.o: R2.cpp tp3_1_1.cpp
#    $(CXX) $(CXXFLAGS) R2.cpp tp3_1_1.cpp

#1.1: R2.o tp3_1_1.o
#    $(CXX) R2.o tp3_1_1.o -o $(EXECUTABLE)
    
#1.2: 
    

#1.3: 
    

#2.1: 
    

#2.2:
    

#2.3:
#	$(CXX) $^ -o $@ $(CXXFLAGS) $(LDFLAGS) $(LDLIBS) 

clean:
		rm -rf $(OBJECTS) *~
